const nameGirl = 'To:Anh_Ang';
const giftUrl = 'https://www.facebook.com/groups/165460116804572';
const eventName = 'Happy 8/3 !!!';
const titleCard = 'For Lan Anh';
const contentCard = '</br> </br> Lan Anh nè, em biết hông ... </br>Thế giới này đã trở nên đẹp hơn từ ngày em xuất hiện!Anh rất vui và mong sớm đến ngày tái ngộ! Mọi thứ đã lên kế hoạch sẵn, chờ chút nữa nha. Ngày Quốc tế Phụ nữ, chúc em những lời chúc tốt đẹp nhất, luôn xinh đẹp, hạnh phúc và vui vẻ không chỉ vào ngày 8/3 và cả những ngày khác nữa.</br> From 07.29 with luv';
const giftImage = 'lananh.jpg';
const giftBg = 'valentines.jpg'
const base64 = '';
const giftImageBase64 = "data:image/jpg;base64, " + base64;